<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVzdIyIZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVzdIyIZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVzdIyIZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVzdIyIZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVzdIyIZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'VzdIyIZ',
    'container.build_id' => '416469eb',
    'container.build_time' => 1607541101,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVzdIyIZ');
